app:
  welcome-message: "Welcome to PRODUCTION Environment!"
  description: "Production configuration for Spring Cloud Config"
  version: "1.0.0-prod"

my:
  secret: "prod-secret-key-abcde"

server:
  port: 8080

logging:
  level:
    com.example: INFO
