# Настройки для профиля 'prod'
app:
  welcome-message: "Hello from PROD profile! System is running in production mode!"
  description: "This configuration is for production environment. Be careful!"

server:
  port: 8082 # Для prod тоже свой порт
