app:
  welcome-message: "Welcome to DEV Environment!"
  description: "Development configuration for Spring Cloud Config"
  version: "1.0.0-dev"

my:
  secret: "dev-secret-key-67890"

server:
  port: 8081
